spring.application.name=ScopeIndia
server.port=8080
spring.mvc.view.prefix=src/main/resources/templates
spring.mvc.view.suffix=.html
spring.datasource.driverClassname=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.jpa.properties.hibernate.Dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.mvc.static-path-pattern=/static/**
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=suryashaji488@gmail.com
spring.mail.password=gglocsnlxbxnwwzp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB